Issue#17  REQ 3.1   fix build failure  60689 [ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.46 s <<< FAILURE! - in gft.mentoring.sap.model.SAPInputTest  60689 [ERROR] exceptionFileIsLocked  Time elapsed: 1.101 s  <<< FAILURE!  org.opentest4j.AssertionFailedError: expected: <The process cannot access the file because another process has locked a portion of the file> but was: <null>  	at gft.mentoring.sap.model.SAPInputTest.exceptionFileIsLocked(SAPInputTest.java:70)